secs

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,23 +1,25 @@
 #!/usr/bin/env bash
 # Serve a page that would return a Hello World string
 
-echo -e "Updating and installing Nginx.\n"
-sudo apt-get update -y -qq && \
-	 sudo apt-get install nginx -y
+apt-get update
+apt-get install -y nginx
 
-echo -e "\nSetting up some minor stuff.\n"
+# Check if Nginx is installed successfully
+if [ $? -ne 0 ]; then
+    echo "Error: Failed to install Nginx."
+    exit 1
+fi
 
-sudo service nginx start
+# Start Nginx
+/usr/sbin/nginx
 
-sudo ufw allow 'Nginx HTTP'
+# Check if Nginx is running
+if ! pgrep -x "nginx" >/dev/null; then
+    echo "Error: Nginx failed to start."
+    exit 1
+fi
 
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+echo "Hello World!" > /var/www/html/index.html
 
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
 
-echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
-
-sudo service nginx restart
-
-echo -e "\nCompleted. ✅\n"
+/usr/sbin/nginx -s reload
